# @package _global_
defaults:
  - _self_

authenticate: ???
port: ???

modules:
  example_module:
    _target_: csp_gateway.server.demo.ExampleModule
  example_module_feedback:
    _target_: csp_gateway.server.demo.ExampleModuleFeedback
  example_custom_table:
    _target_: csp_gateway.server.demo.ExampleCustomTable
  mount_channels_graph:
    _target_: csp_gateway.MountChannelsGraph
  mount_controls:
    _target_: csp_gateway.MountControls
  mount_outputs:
    _target_: csp_gateway.MountOutputsFolder
  mount_perspective_tables:
    _target_: csp_gateway.MountPerspectiveTables
    perspective_field: "perspective"
    layouts:
      Server Defined Layout: '{"sizes":[1],"detail":{"main":{"type":"split-area","orientation":"horizontal","children":[{"type":"split-area","orientation":"vertical","children":[{"type":"tab-area","widgets":["PERSPECTIVE_GENERATED_ID_1"],"currentIndex":0},{"type":"tab-area","widgets":["PERSPECTIVE_GENERATED_ID_4"],"currentIndex":0}],"sizes":[0.5,0.5]},{"type":"split-area","orientation":"vertical","children":[{"type":"tab-area","widgets":["PERSPECTIVE_GENERATED_ID_3"],"currentIndex":0},{"type":"tab-area","widgets":["PERSPECTIVE_GENERATED_ID_5"],"currentIndex":0}],"sizes":[0.5,0.5]}],"sizes":[0.5,0.5]}},"mode":"globalFilters","viewers":{"PERSPECTIVE_GENERATED_ID_1":{"plugin":"Datagrid","plugin_config":{"columns":{},"editable":false,"scroll_lock":true},"settings":false,"theme":"Pro Dark","group_by":["id"],"split_by":[],"columns":["timestamp","x","y"],"filter":[],"sort":[["timestamp","desc"]],"expressions":[],"aggregates":{"timestamp":"last","x":"last","id":"last","y":"last"},"master":false,"title":"basket","table":"basket","linked":false},"PERSPECTIVE_GENERATED_ID_4":{"plugin":"Datagrid","plugin_config":{"columns":{},"editable":false,"scroll_lock":true},"settings":false,"theme":"Pro Dark","group_by":["id"],"split_by":[],"columns":["timestamp","x","y"],"filter":[],"sort":[["timestamp","desc"]],"expressions":[],"aggregates":{"timestamp":"last","x":"last","id":"last","y":"last"},"master":false,"title":"example_list","table":"example_list","linked":false},"PERSPECTIVE_GENERATED_ID_3":{"plugin":"Datagrid","plugin_config":{"columns":{},"editable":false,"scroll_lock":true},"settings":false,"theme":"Pro Dark","group_by":["id"],"split_by":[],"columns":["timestamp","x","y"],"filter":[],"sort":[["timestamp","desc"]],"expressions":[],"aggregates":{"id":"last","x":"last","timestamp":"last","y":"last"},"master":false,"title":"example","table":"example","linked":false},"PERSPECTIVE_GENERATED_ID_5":{"plugin":"Datagrid","plugin_config":{"columns":{},"editable":false,"scroll_lock":true},"settings":false,"theme":"Pro Dark","group_by":["id"],"split_by":[],"columns":["timestamp","x","y"],"filter":[],"sort":[["timestamp","desc"]],"expressions":[],"aggregates":{"id":"last","timestamp":"last","x":"last","y":"last"},"master":false,"title":"never_ticks","table":"never_ticks","linked":false}}}'  # noqa: E501
    update_interval: 00:00:02
  mount_rest_routes:
    _target_: csp_gateway.MountRestRoutes
    force_mount_all: True
  mount_websocket_routes:
    _target_: csp_gateway.MountWebSocketRoutes
  mount_api_key_middleware:
    _target_: csp_gateway.MountAPIKeyMiddleware

gateway:
  _target_: csp_gateway.Gateway
  settings:
    PORT: ${port}
    AUTHENTICATE: ${authenticate}
    UI: True
    API_KEY: "12345"
  modules:
    - /modules/example_module
    - /modules/example_module_feedback
    - /modules/example_custom_table
    - /modules/mount_channels_graph
    - /modules/mount_controls
    - /modules/mount_outputs
    - /modules/mount_perspective_tables
    - /modules/mount_rest_routes
    - /modules/mount_websocket_routes
    - /modules/mount_api_key_middleware
  channels:
    _target_: csp_gateway.server.demo.ExampleGatewayChannels

hydra:
#   searchpath:
  run:
    dir: outputs/${oc.env:HOSTNAME}_${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
